package pwo.projekt.gui;

import java.io.File;
import java.io.IOException;
import java.lang.reflect.Array;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import pwo.projekt.stats.FileMetadata;
import pwo.projekt.stats.FileStatistics;
import pwo.projekt.stats.utils.FileType;

/**
 *
 * @author Michał Moń
 * Klasa sluzaca do wyswietlania aplikacji w trybie interfejsu graficznego
 */
public class ProjektGui extends javax.swing.JFrame {

    private static final String APP_NAME = "Praktyka wytwarzania oprogramowania - projekt";
    private static int DEFAULT_WIDTH = 850, DEFAULT_HEIGHT = 600;
    private final JFileChooser openFileChooser;
    private String filename1 = "";
    private String filename2 = "";
    private String path1 = "";
    private String path2 = "";
    private Object[] filesData = new Object[20];
    private Object[] filesDataSecond = new Object[20];
    
    /**
     * Tworzy nowy formularz klasy 
     * @see #ProjektGui
     */
    public ProjektGui() {
        initComponents();
        openFileChooser = new JFileChooser();
        openFileChooser.setCurrentDirectory(new File("C:\\"));
        openFileChooser.setFileFilter(new FileNameExtensionFilter("Plik tekstowy .txt", "txt"));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        OpenSecondFile = new javax.swing.JButton();
        OpenFirstFile = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        FirstFileStatsButton = new javax.swing.JButton();
        SecondFileStatsButton = new javax.swing.JButton();
        messageLabel1 = new javax.swing.JLabel();
        messageLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        firstFileStatsList = new javax.swing.JList<>();
        FirstFileResultLabel = new javax.swing.JLabel();
        SecondFileResultLabel = new javax.swing.JLabel();
        SecondFileResult = new javax.swing.JTextField();
        FirstFileResult = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        secondFileStatsList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Projekt PWO - statystyki plików tekstowych");

        jLabel2.setText("Autorzy:");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setText("Konrad Miziński");

        jLabel4.setText("Eliza Kozioł");

        jLabel5.setText("Michał Moń");

        OpenSecondFile.setText("Wybierz plik...");
        OpenSecondFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenSecondFileActionPerformed(evt);
            }
        });

        OpenFirstFile.setText("Wybierz plik...");
        OpenFirstFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenFirstFileActionPerformed(evt);
            }
        });

        jLabel6.setText("Plik 1:");

        jLabel7.setText("Plik 2:");

        FirstFileStatsButton.setText("Oblicz statystyki");
        FirstFileStatsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstFileStatsButtonActionPerformed(evt);
            }
        });

        SecondFileStatsButton.setText("Oblicz statystyki");
        SecondFileStatsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecondFileStatsButtonActionPerformed(evt);
            }
        });

        firstFileStatsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Data utworzenia", "Czas ostatniego dostępu",
                "Czas ostatniej modyfikacji", "Rodzaj pliku", "Rozmiar pliku",
                "Autor", "Liczba wierszy", "Liczba wyrazów",
                "Liczba znaków", "Liczba znaków (bez białych)",
                "Liczba znaków ASCII", "Liczba znaków nie-ASCII",
                "Liczba polskich znaków", "Procent polskich znaków",
                "Średnia długość wyrazu", "Średnia ilość wyrazów w wierszu",
                "Średnia ilość znaków w wierszu", "Najczęstszy znak",
                "Najrzadszy znak"};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        firstFileStatsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstFileStatsListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(firstFileStatsList);

        FirstFileResultLabel.setText("Dane:");

        SecondFileResultLabel.setText("Dane:");

        SecondFileResult.setEditable(false);

        FirstFileResult.setEditable(false);

        jLabel9.setText("Wybierz statystykę, żeby ją wyświetlić");

        jLabel11.setText("Wybierz statystykę, żeby ją wyświetlić");

        secondFileStatsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Data utworzenia", "Czas ostatniego dostępu",
                "Czas ostatniej modyfikacji", "Rodzaj pliku", "Rozmiar pliku",
                "Autor", "Liczba wierszy", "Liczba wyrazów",
                "Liczba znaków", "Liczba znaków (bez białych)",
                "Liczba znaków ASCII", "Liczba znaków nie-ASCII",
                "Liczba polskich znaków", "Procent polskich znaków",
                "Średnia długość wyrazu", "Średnia ilość wyrazów w wierszu",
                "Średnia ilość znaków w wierszu", "Najczęstszy znak",
                "Najrzadszy znak"};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        secondFileStatsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                secondFileStatsListMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(secondFileStatsList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FirstFileResult, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FirstFileResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FirstFileStatsButton)
                                    .addComponent(OpenFirstFile, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(messageLabel1))))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(messageLabel2)
                                    .addComponent(OpenSecondFile, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SecondFileStatsButton)))
                            .addComponent(jLabel11)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SecondFileResult, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SecondFileResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(SecondFileResultLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SecondFileResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(226, 226, 226))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(OpenSecondFile)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SecondFileStatsButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(messageLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addComponent(jLabel11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OpenFirstFile)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FirstFileStatsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messageLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FirstFileResultLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FirstFileResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenSecondFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenSecondFileActionPerformed
        int returnValue = openFileChooser.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION){
                filename2 = openFileChooser.getSelectedFile().getName();
                path2 = openFileChooser.getSelectedFile().getAbsolutePath();
                messageLabel2.setText("Wczytano plik: " + filename2);
        }
        else{
            messageLabel2.setText("Nie wybrano pliku!");
        }
    }//GEN-LAST:event_OpenSecondFileActionPerformed

    private void OpenFirstFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenFirstFileActionPerformed
        int returnValue = openFileChooser.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION){
                filename1 = openFileChooser.getSelectedFile().getName();
                path1 = openFileChooser.getSelectedFile().getAbsolutePath();
                messageLabel1.setText("Wczytano plik: " + filename1);
        }
        else{
            messageLabel1.setText("Nie wybrano pliku!");
        }
    }//GEN-LAST:event_OpenFirstFileActionPerformed

    private void FirstFileStatsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstFileStatsButtonActionPerformed

        FileMetadata metadata;
        try {
            metadata = new FileMetadata(path1);
            filesData[0] = metadata.getCreationTime();
            filesData[1] = metadata.getLastAccessTime();
            filesData[2] = metadata.getLastModificationTime();
            filesData[3] = metadata.getFileType();
            filesData[4] = metadata.getFileSize();
            filesData[5] = metadata.getOwner();
            FileStatistics stats = new FileStatistics(path1);
            filesData[6] = stats.getNumOfLines();
            filesData[7] = stats.getNumOfWords();
            filesData[8] = stats.getNumOfChars();
            filesData[9] = stats.getNumOfNonWhiteChars();
            filesData[10] = stats.getNumOfAsciiChars();
            filesData[11] = stats.getNumOfNonAsciiChars();
            filesData[12] = stats.getNumOfPolishChars();
            filesData[13] = stats.percentageOfPolishChars();
            filesData[14] = stats.getAvgWordLength();
            filesData[15] = stats.getAvgWordsInLine();
            filesData[16] = stats.getAvgCharsInLine();
            filesData[17] = stats.getMostFrequentCharacter();
            filesData[18] = stats.getLeastFrequentCharacter();
            filesData[19] = stats.getCharsStats();
            messageLabel1.setText("Udało się obliczyć statystyki pliku!");
        } catch (IOException ex) {
            Logger.getLogger(ProjektGui.class.getName()).log(Level.SEVERE, null, ex);
            messageLabel1.setText("Nie udało się obliczyć statystyk!");
        }
    }//GEN-LAST:event_FirstFileStatsButtonActionPerformed

    private void SecondFileStatsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecondFileStatsButtonActionPerformed
        
        FileMetadata metadata;
        try {
            metadata = new FileMetadata(path2);
            filesDataSecond[0] = metadata.getCreationTime();
            filesDataSecond[1] = metadata.getLastAccessTime();
            filesDataSecond[2] = metadata.getLastModificationTime();
            filesDataSecond[3] = metadata.getFileType();
            filesDataSecond[4] = metadata.getFileSize();
            filesDataSecond[5] = metadata.getOwner();
            FileStatistics stats = new FileStatistics(path2);
            filesDataSecond[6] = stats.getNumOfLines();
            filesDataSecond[7] = stats.getNumOfWords();
            filesDataSecond[8] = stats.getNumOfChars();
            filesDataSecond[9] = stats.getNumOfNonWhiteChars();
            filesDataSecond[10] = stats.getNumOfAsciiChars();
            filesDataSecond[11] = stats.getNumOfNonAsciiChars();
            filesDataSecond[12] = stats.getNumOfPolishChars();
            filesDataSecond[13] = stats.percentageOfPolishChars();
            filesDataSecond[14] = stats.getAvgWordLength();
            filesDataSecond[15] = stats.getAvgWordsInLine();
            filesDataSecond[16] = stats.getAvgCharsInLine();
            filesDataSecond[17] = stats.getMostFrequentCharacter();
            filesDataSecond[18] = stats.getLeastFrequentCharacter();
            filesDataSecond[19] = stats.getCharsStats();
            messageLabel2.setText("Udało się obliczyć statystyki pliku!");
        } catch (IOException ex) {
            Logger.getLogger(ProjektGui.class.getName()).log(Level.SEVERE, null, ex);
            messageLabel2.setText("Nie udało się obliczyć statystyk!");
        }
    }//GEN-LAST:event_SecondFileStatsButtonActionPerformed

    private void firstFileStatsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstFileStatsListMouseClicked

        String sel = "";
        int selectedIx = this.firstFileStatsList.getSelectedIndex();      
        sel = filesData[selectedIx].toString();
        //System.out.println(sel);
        FirstFileResult.setText(sel);
    }//GEN-LAST:event_firstFileStatsListMouseClicked

    private void secondFileStatsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_secondFileStatsListMouseClicked
        String sel = "";
        int selectedIx = this.secondFileStatsList.getSelectedIndex();      
        sel = filesDataSecond[selectedIx].toString();
        //System.out.println(sel);
        SecondFileResult.setText(sel);
    }//GEN-LAST:event_secondFileStatsListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjektGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjektGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjektGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjektGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProjektGui gui = new ProjektGui();
                gui.setTitle(APP_NAME);
                gui.setSize(DEFAULT_WIDTH, DEFAULT_HEIGHT);
                gui.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FirstFileResult;
    private javax.swing.JLabel FirstFileResultLabel;
    private javax.swing.JButton FirstFileStatsButton;
    private javax.swing.JButton OpenFirstFile;
    private javax.swing.JButton OpenSecondFile;
    private javax.swing.JTextField SecondFileResult;
    private javax.swing.JLabel SecondFileResultLabel;
    private javax.swing.JButton SecondFileStatsButton;
    private javax.swing.JList<String> firstFileStatsList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel messageLabel1;
    private javax.swing.JLabel messageLabel2;
    private javax.swing.JList<String> secondFileStatsList;
    // End of variables declaration//GEN-END:variables
}
