/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pwo.projekt.gui;

import java.io.File;
import java.io.IOException;
import java.lang.reflect.Array;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import pwo.projekt.stats.FileMetadata;
import pwo.projekt.stats.FileStatistics;
import pwo.projekt.stats.utils.FileType;

/**
 *
 * @author Michał Moń
 */
public class ProjektGui extends javax.swing.JFrame {

    private static final String APP_NAME = "Praktyka wytwarzania oprogramowania - projekt";
    private static int DEFAULT_WIDTH = 800, DEFAULT_HEIGHT = 600;
    private final JFileChooser openFileChooser;
    private String filename1 = "";
    private String filename2 = "";
    private String path1 = "";
    private String path2 = "";
    /**
     * Creates new form ProjektGui
     */
    public ProjektGui() {
        initComponents();
        openFileChooser = new JFileChooser();
        openFileChooser.setCurrentDirectory(new File("C:\\"));
        openFileChooser.setFileFilter(new FileNameExtensionFilter("Plik tekstowy .txt", "txt"));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        OpenSecondFile = new javax.swing.JButton();
        OpenFirstFile = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        FirstFileStatsButton = new javax.swing.JButton();
        SecondFileStatsButton = new javax.swing.JButton();
        messageLabel1 = new javax.swing.JLabel();
        messageLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Projekt PWO - statystyki plików tekstowych");

        jLabel2.setText("Autorzy:");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setText("Konrad Miziński");

        jLabel4.setText("Eliza Kozioł");

        jLabel5.setText("Michał Moń");

        OpenSecondFile.setText("Wybierz plik...");
        OpenSecondFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenSecondFileActionPerformed(evt);
            }
        });

        OpenFirstFile.setText("Wybierz plik...");
        OpenFirstFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenFirstFileActionPerformed(evt);
            }
        });

        jLabel6.setText("Plik 1:");

        jLabel7.setText("Plik 2:");

        FirstFileStatsButton.setText("Oblicz statystyki");
        FirstFileStatsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstFileStatsButtonActionPerformed(evt);
            }
        });

        SecondFileStatsButton.setText("Oblicz statystyki");
        SecondFileStatsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecondFileStatsButtonActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Creation Time", "Last Access Time",
                "Last Modification Time", "File Type", "File Size",
                "Owner", "Number of lines", "Number of words",
                "Number of characters", "Number of non-white chars",
                "Number of ASCII chars", "Number of non-ASCII chars",
                "Number of polish chars", "percentage of polish chars",
                "Average word length", "Average words in line",
                "Average chars in line", "Most frequent character",
                "Least frequent character"};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jList1);

        jLabel8.setText("Dane:");

        jLabel10.setText("Dane:");

        jLabel9.setText("Wybierz statystykę, żeby ją wyświetlić");

        jLabel11.setText("Wybierz statystykę, żeby ją wyświetlić");

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Creation Time", "Last Access Time",
                "Last Modification Time", "File Type", "File Size",
                "Owner", "Number of lines", "Number of words",
                "Number of characters", "Number of non-white chars",
                "Number of ASCII chars", "Number of non-ASCII chars",
                "Number of polish chars", "percentage of polish chars",
                "Average word length", "Average words in line",
                "Average chars in line", "Most frequent character",
                "Least frequent character"};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList3MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jList3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(FirstFileStatsButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(messageLabel1)
                                    .addComponent(OpenFirstFile, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel9))))
                .addGap(193, 193, 193)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(jTextField1))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SecondFileStatsButton)
                            .addComponent(OpenSecondFile, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(messageLabel2))
                        .addGap(119, 119, 119))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(324, 324, 324)
                    .addComponent(jLabel1))
                .addGroup(layout.createSequentialGroup()
                    .addGap(331, 331, 331)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(OpenSecondFile)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(messageLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SecondFileStatsButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OpenFirstFile)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messageLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FirstFileStatsButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenSecondFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenSecondFileActionPerformed
        int returnValue = openFileChooser.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION){
                filename2 = openFileChooser.getSelectedFile().getName();
                path2 = openFileChooser.getSelectedFile().getAbsolutePath();
                messageLabel2.setText("Wczytano plik: " + filename2 + " Ścieżka: " + path2);
        }
        else{
            messageLabel2.setText("Nie wybrano pliku!");
        }
    }//GEN-LAST:event_OpenSecondFileActionPerformed

    private void OpenFirstFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenFirstFileActionPerformed
        int returnValue = openFileChooser.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION){
                filename1 = openFileChooser.getSelectedFile().getName();
                path1 = openFileChooser.getSelectedFile().getAbsolutePath();
                messageLabel1.setText("Wczytano plik: " + filename1 + " Ścieżka: " + path1);
        }
        else{
            messageLabel1.setText("Nie wybrano pliku!");
        }
    }//GEN-LAST:event_OpenFirstFileActionPerformed

    private void FirstFileStatsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstFileStatsButtonActionPerformed
        Object[] filesData = new Object[20];
        FileMetadata metadata;
        try {
            metadata = new FileMetadata(path1);
            filesData[0] = metadata.getCreationTime();
            filesData[1] = metadata.getLastAccessTime();
            filesData[2] = metadata.getLastModificationTime();
            filesData[3] = metadata.getFileType();
            filesData[4] = metadata.getFileSize();
            filesData[5] = metadata.getOwner();
            FileStatistics stats = new FileStatistics(path1);
            filesData[6] = stats.getNumOfLines();
            filesData[7] = stats.getNumOfWords();
            filesData[8] = stats.getNumOfChars();
            filesData[9] = stats.getNumOfNonWhiteChars();
            filesData[10] = stats.getNumOfAsciiChars();
            filesData[11] = stats.getNumOfNonAsciiChars();
            filesData[12] = stats.getNumOfPolishChars();
            filesData[13] = stats.percentageOfPolishChars();
            filesData[14] = stats.getAvgWordLength();
            filesData[15] = stats.getAvgWordsInLine();
            filesData[16] = stats.getAvgCharsInLine();
            filesData[17] = stats.getMostFrequentCharacter();
            filesData[18] = stats.getLeastFrequentCharacter();
            filesData[19] = stats.getCharsStats();
            messageLabel1.setText(filesData[7].toString());
        } catch (IOException ex) {
            Logger.getLogger(ProjektGui.class.getName()).log(Level.SEVERE, null, ex);
            messageLabel1.setText("Nie udało się obliczyć statystyk!");
        }
    }//GEN-LAST:event_FirstFileStatsButtonActionPerformed

    private void SecondFileStatsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecondFileStatsButtonActionPerformed
        Object[] filesData = new Object[20];
        FileMetadata metadata;
        try {
            metadata = new FileMetadata(path2);
            filesData[0] = metadata.getCreationTime();
            filesData[1] = metadata.getLastAccessTime();
            filesData[2] = metadata.getLastModificationTime();
            filesData[3] = metadata.getFileType();
            filesData[4] = metadata.getFileSize();
            filesData[5] = metadata.getOwner();
            FileStatistics stats = new FileStatistics(path2);
            filesData[6] = stats.getNumOfLines();
            filesData[7] = stats.getNumOfWords();
            filesData[8] = stats.getNumOfChars();
            filesData[9] = stats.getNumOfNonWhiteChars();
            filesData[10] = stats.getNumOfAsciiChars();
            filesData[11] = stats.getNumOfNonAsciiChars();
            filesData[12] = stats.getNumOfPolishChars();
            filesData[13] = stats.percentageOfPolishChars();
            filesData[14] = stats.getAvgWordLength();
            filesData[15] = stats.getAvgWordsInLine();
            filesData[16] = stats.getAvgCharsInLine();
            filesData[17] = stats.getMostFrequentCharacter();
            filesData[18] = stats.getLeastFrequentCharacter();
            filesData[19] = stats.getCharsStats();
            messageLabel2.setText(filesData[7].toString());
        } catch (IOException ex) {
            Logger.getLogger(ProjektGui.class.getName()).log(Level.SEVERE, null, ex);
            messageLabel2.setText("Nie udało się obliczyć statystyk!");
        }
    }//GEN-LAST:event_SecondFileStatsButtonActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked

    //indeks = tablica? TAK ZROBIC
    Object sel =null;

    int[] selectedIx = this.jList1.getSelectedIndices();      

    for (int i = 0; i < selectedIx.length; i++) {
        sel = jList1.getModel().getElementAt(selectedIx[i]);
    }

    System.out.println(sel);
    }//GEN-LAST:event_jList1MouseClicked

    private void jList3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jList3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjektGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjektGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjektGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjektGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProjektGui gui = new ProjektGui();
                gui.setTitle(APP_NAME);
                gui.setSize(DEFAULT_WIDTH, DEFAULT_HEIGHT);
                gui.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FirstFileStatsButton;
    private javax.swing.JButton OpenFirstFile;
    private javax.swing.JButton OpenSecondFile;
    private javax.swing.JButton SecondFileStatsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel messageLabel1;
    private javax.swing.JLabel messageLabel2;
    // End of variables declaration//GEN-END:variables
}
